<section class="page__inner page__view">
    
    <div class="page__user">
        <h2 class="title">Novo Ranking</h2>
    
        <form method="post" action="/categoria/store">
            <input class="input" type="text" name="categoria" minlength="3" required placeholder="Titulo do ranking">
    
            <button class="btn" type="submit">Criar</button>
        </form>
    </div>

</section>