<section class="page__inner">

    <div class="page__user">
        <h2 class="title">Registrar</h2>

<?php if(isset($_GET['erro']) && $_GET['erro'] == 'senha') { ?>

        <p class="erro"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> A confirmação de password não confere.</p>

<?php } ?>

<?php if(isset($_GET['erro']) && $_GET['erro'] == 'email') { ?>

        <p class="erro"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> E-mail ja cadastrado.</p>

<?php } ?>
    
        <form method="post" action="/user/store">
            <input class="input" type="text" name="nome" required minlength="3" placeholder="Digite seu nome">
            <input class="input" type="email" name="email" required placeholder="Digite seu e-mail">
            <input class="input" type="password" name="senha" required minlength="3" placeholder="Digite uma senha">
            <input class="input" type="password" name="confirm-senha" required minlength="3" placeholder="Confirme a senha">
    
            <button class="btn" type="submit">Registrar</button>
        </form>


    
        <div class="align-center my-2">
            <a class="link" href="/">fazer login</a>
        </div>
    </div>

</section>