<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Marcos de Oliveira">
    <meta name="description" content="Projeto de ranking pessoal para definir seus rankings.">
    
    <title>Projeto de Ranking pessoal</title>

    <link rel="stylesheet" type="text/css" href="/src/css/main.css">

    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <script src="/src/js/menu.js"></script>
</head>
<body class="page">
    <header class="header page__inner">
        <h2>Projeto Ranking</h2>
        
<?php if(isset($_SESSION['autenticado'])) { ?>

        <nav class="navbar">
            <a class="navbar__link" href="/categoria/home">Home</a>
            <a class="navbar__link" href="/categoria/create">Novo Ranking</a>
            <a class="navbar__link" href="/user/logout">Sair</a>
        </nav>

<?php } ?>

        <div class="bar-btn">
            <span class="bar-btn__line"></span>
            <span class="bar-btn__line"></span>
            <span class="bar-btn__line"></span>
        </div>
    </header>

    <main class="mt-5 mb-10">
        <?=$content?>
    </main>

    <footer class="footer">
        <p class="my-2">Todos os direitos reservados</p>
    </footer>
</body>
</html>